/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.hospitaladminrole;

import business.db4outil.DB4OUtil;
import business.config.EcoSystem;
import business.enterprise.Enterprise;
import business.network.Network;
import business.useraccount.UserAccount;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;


public class UpdateHospitalStaffJPanel extends javax.swing.JPanel {

    /**
     * Creates new form UpdateHospitalStaffJPanel
     */    
    JPanel userProcessContainer;
    EcoSystem ecosystem;
    UserAccount hospitalAdminAccount;
    UserAccount hospitalStaff;
    Enterprise currentEnterprise;
    private DB4OUtil dB4OUtil = DB4OUtil.getInstance();
    public UpdateHospitalStaffJPanel(JPanel userProcessContainer, EcoSystem ecosystem, UserAccount hospitalAdminAccount, UserAccount hospitalStaff) {
        initComponents();
        this.userProcessContainer=userProcessContainer;
        this.ecosystem=ecosystem;
        this.hospitalAdminAccount = hospitalAdminAccount;
        this.hospitalStaff = hospitalStaff;
        initialize();
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtHospitalStaffUsername = new javax.swing.JTextField();
        txtHospitalStaffPhoneNo = new javax.swing.JTextField();
        txtHospitalStaffPassword = new javax.swing.JTextField();
        txtHospitalStaffName = new javax.swing.JTextField();
        btnAddHospitalStaff = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        lblEnterpriseName = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 240));

        txtHospitalStaffUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHospitalStaffUsernameActionPerformed(evt);
            }
        });

        txtHospitalStaffPhoneNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHospitalStaffPhoneNoActionPerformed(evt);
            }
        });

        txtHospitalStaffPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHospitalStaffPasswordActionPerformed(evt);
            }
        });

        txtHospitalStaffName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHospitalStaffNameActionPerformed(evt);
            }
        });

        btnAddHospitalStaff.setText("Update");
        btnAddHospitalStaff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddHospitalStaffActionPerformed(evt);
            }
        });

        jLabel1.setText("Hospital Staff Name");

        jLabel2.setText("Hospital Staff Username");

        jLabel3.setText("Hospital Staff Phone No.");

        jLabel4.setText("Hospital Staff Password");

        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/assets/images/medicalteam.jpg"))); // NOI18N

        lblEnterpriseName.setText("Enterprise Name");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnBack)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnAddHospitalStaff)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel4))
                                .addGap(29, 29, 29)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtHospitalStaffPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtHospitalStaffPhoneNo, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtHospitalStaffUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtHospitalStaffName, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblEnterpriseName))))
                        .addGap(80, 80, 80)
                        .addComponent(jLabel5)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBack)
                    .addComponent(lblEnterpriseName))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtHospitalStaffName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtHospitalStaffUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtHospitalStaffPhoneNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtHospitalStaffPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(btnAddHospitalStaff))
                    .addComponent(jLabel5))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtHospitalStaffUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHospitalStaffUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHospitalStaffUsernameActionPerformed

    private void txtHospitalStaffPhoneNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHospitalStaffPhoneNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHospitalStaffPhoneNoActionPerformed

    private void txtHospitalStaffPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHospitalStaffPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHospitalStaffPasswordActionPerformed

    private void txtHospitalStaffNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHospitalStaffNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHospitalStaffNameActionPerformed

    private void btnAddHospitalStaffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddHospitalStaffActionPerformed
        // TODO add your handling code here:
        if(txtHospitalStaffName.getText().isEmpty()){
            JOptionPane.showMessageDialog(null,"Please enter hospital staff name!");
            return;
        }
        if(txtHospitalStaffUsername.getText().isEmpty()){
            JOptionPane.showMessageDialog(null,"Please enter hospital staff username!");
            return;
        }
        for(UserAccount ua:this.ecosystem.getUserAccountDirectory().getUserAccountList()){
            if(ua.getUsername().equals(txtHospitalStaffUsername.getText())&&!this.hospitalStaff.getUsername().equals(txtHospitalStaffUsername.getText())){
                JOptionPane.showMessageDialog(null,"Username already exists... please enter a different username!");
                return;
            }
        }
        if(txtHospitalStaffPhoneNo.getText().isEmpty()){
            JOptionPane.showMessageDialog(null,"Please enter hospital staff phone Number!");
            return;
        }
        if(txtHospitalStaffPassword.getText().isEmpty()){
            JOptionPane.showMessageDialog(null,"Please enter hospital staff password!");
            return;
        }
        for(UserAccount ua:this.ecosystem.getUserAccountDirectory().getUserAccountList()){
            if(ua.getUsername().equals(this.hospitalStaff.getUsername())){
                ua.getUser().setName(txtHospitalStaffName.getText());
                ua.getUser().setPhone(txtHospitalStaffPhoneNo.getText());
                ua.setUsername(txtHospitalStaffUsername.getText());
                ua.setPassword(txtHospitalStaffPassword.getText());
                break;
            }
        }

        dB4OUtil.storeSystem(ecosystem);

        isEnabled(false);

        JOptionPane.showMessageDialog(null,"Hospital staff updated successfully!");
        return;
        }
        public void initialize(){
            txtHospitalStaffName.setText(this.hospitalStaff.getUser().getName());
            txtHospitalStaffPassword.setText(this.hospitalStaff.getPassword());
            txtHospitalStaffPhoneNo.setText(this.hospitalStaff.getUser().getPhone());
            txtHospitalStaffUsername.setText(this.hospitalStaff.getUsername());
            outerloop:
            for(Network n:this.ecosystem.getNetworkList()){
                for(Enterprise e :n.getEnterpriseDirectory().getEnterpriseList()){
                    if(e.getUserAccount().getUsername().equals(this.hospitalAdminAccount.getUsername())){
                        this.currentEnterprise = e;
                        break outerloop;
                    }
                }
            }
            lblEnterpriseName.setText(this.currentEnterprise.getName());
    }//GEN-LAST:event_btnAddHospitalStaffActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        this.userProcessContainer.remove(this);
        CardLayout layout =(CardLayout) this.userProcessContainer.getLayout();
        Component [] comps = this.userProcessContainer.getComponents();
        for(Component comp : comps){
            if(comp instanceof HospitalAdminRoleWorkAreaJPanel){
                HospitalAdminRoleWorkAreaJPanel harwajp =(HospitalAdminRoleWorkAreaJPanel) comp;
                harwajp.populateDoctors();
                harwajp.populateHospitalStaff();
            }
        }
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    public void isEnabled(boolean b){
        txtHospitalStaffName.setEnabled(b);
        txtHospitalStaffPassword.setEnabled(b);
        txtHospitalStaffPhoneNo.setEnabled(b);
        txtHospitalStaffUsername.setEnabled(b);
//        txtDisasterManagmt.setEnabled(b);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddHospitalStaff;
    private javax.swing.JButton btnBack;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel lblEnterpriseName;
    private javax.swing.JTextField txtHospitalStaffName;
    private javax.swing.JTextField txtHospitalStaffPassword;
    private javax.swing.JTextField txtHospitalStaffPhoneNo;
    private javax.swing.JTextField txtHospitalStaffUsername;
    // End of variables declaration//GEN-END:variables
}
