/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.systemadminrole;

import business.db4outil.DB4OUtil;
import business.config.EcoSystem;
import business.user.User;
import business.network.Network;
import business.role.CityAdminRole;
import business.useraccount.UserAccount;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;


public class UpdateCityJPanel extends javax.swing.JPanel {

    /**
     * Creates new form UpdateCityJPanel
     */
    JPanel userProcessContainer;
    EcoSystem ecosystem;
    Network network,tempNetwork;
    private DB4OUtil dB4OUtil = DB4OUtil.getInstance();
    public UpdateCityJPanel() {
        initComponents();
    }

    UpdateCityJPanel(JPanel userProcessContainer, EcoSystem ecosystem, Network network) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.ecosystem = ecosystem;
        this.network = network;
        this.tempNetwork = new Network();
        this.tempNetwork.setZipCodes(this.network.getZipCodes());
        populate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtZipCode = new javax.swing.JTextField();
        txtCityName = new javax.swing.JTextField();
        btnAddCity = new javax.swing.JButton();
        txtCityAdminName = new javax.swing.JTextField();
        txtCityAdminUserName = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtCityAdminPassword = new javax.swing.JTextField();
        btnAddZipCode = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDirectory = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnDeleteZipCode = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 240));

        jLabel6.setText("Add Zip Code");

        jLabel3.setText("City Admin Username");

        txtCityName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCityNameActionPerformed(evt);
            }
        });

        btnAddCity.setText("Submit City ");
        btnAddCity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddCityActionPerformed(evt);
            }
        });

        txtCityAdminName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCityAdminNameActionPerformed(evt);
            }
        });

        jLabel4.setText("City Admin Password");

        btnAddZipCode.setText("Add Zip Code");
        btnAddZipCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddZipCodeActionPerformed(evt);
            }
        });

        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        tblDirectory.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Zip Code"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblDirectory);

        jLabel1.setText("City Name");

        jLabel2.setText("City Admin Name");

        btnDeleteZipCode.setText("Delete ZipCode");
        btnDeleteZipCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteZipCodeActionPerformed(evt);
            }
        });

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/assets/images/addstate.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel1)
                                            .addComponent(jLabel4))
                                        .addGap(24, 24, 24))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addGap(75, 75, 75)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtCityAdminUserName, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtCityAdminName, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtCityName, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtCityAdminPassword)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                    .addComponent(txtZipCode, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnAddZipCode)))
                            .addComponent(btnAddCity, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnDeleteZipCode, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(45, 45, 45)
                        .addComponent(jLabel5))
                    .addComponent(btnBack))
                .addContainerGap(130, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnBack)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jLabel5))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtCityName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtCityAdminName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtCityAdminUserName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCityAdminPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtZipCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAddZipCode)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDeleteZipCode)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAddCity)))
                .addGap(329, 329, 329))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtCityNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCityNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCityNameActionPerformed

    private void btnAddCityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddCityActionPerformed
        // TODO add your handling code here:
        if(txtCityName.getText().isEmpty()){
            JOptionPane.showMessageDialog(null,"Please enter city name!");
            return;
        }
        
        for(Network n:this.ecosystem.getNetworkList()){
            if(n.getCityName().equals(txtCityName.getText())&&!network.getCityName().equals(txtCityName.getText())){
                JOptionPane.showMessageDialog(null,"This city already exist..enter a different city!");
                return;
            }
        }
        //        txtDisasterManagmt.setText("Disaster Management of" + txtCityName);
        if(txtCityAdminName.getText().isEmpty()){
            JOptionPane.showMessageDialog(null,"Please enter city admin name!");
            return;
        }
        if(txtCityAdminUserName.getText().isEmpty()){
            JOptionPane.showMessageDialog(null,"Please enter city admin username!");
            return;
        }
        for(UserAccount ua:this.ecosystem.getUserAccountDirectory().getUserAccountList()){
            if(ua.getUsername().equals(txtCityAdminUserName.getText())&&!network.getCityAdmin().getUsername().equals(txtCityAdminUserName.getText())){
                JOptionPane.showMessageDialog(null,"Username already exists... please enter a different username!");
                return;
            }
        }
        if(txtCityAdminPassword.getText().isEmpty()){
            JOptionPane.showMessageDialog(null,"Please enter city admin password!");
            return;
        }
        
        if(tblDirectory.getRowCount()==0){
            JOptionPane.showMessageDialog(null,"City should have at least one zipcode!");
            return;
        }
        
        String disasterMangmt = "Disaster Management of " + txtCityName.getText();

        String name = txtCityAdminName.getText();
        String username = txtCityAdminUserName.getText();
        String password = txtCityAdminPassword.getText();

        
        User user = new User();
        user.setName(name);
        UserAccount userAccount = new UserAccount();
        userAccount.setUser(user);
        userAccount.setPassword(password);
        userAccount.setUsername(username);
        userAccount.setRole(new CityAdminRole());
        
        for(User e: this.ecosystem.getUserDirectory().getUserList()){
            if(e.getId() == network.getCityAdmin().getUser().getId()){
                e.setName(name);
            }
        }
        for(UserAccount ua:this.ecosystem.getUserAccountDirectory().getUserAccountList()){
            if(ua.getUsername().equals(network.getCityAdmin().getUsername())){
                ua.setUsername(username);
                ua.setPassword(password);
            }
        }

                for(Network n: this.ecosystem.getNetworkList()){
                    if(n.getName().equals(network.getName())){
                        n.setCityName(txtCityName.getText());
                        n.setName(disasterMangmt);
                        n.setZipCodes(tempNetwork.getZipCodes());
                        break;
                    }
                }  

       dB4OUtil.storeSystem(ecosystem);
//
//        isEditable(false);

        JOptionPane.showMessageDialog(null,"City updated successfully!");
        return;
    }//GEN-LAST:event_btnAddCityActionPerformed

    private void txtCityAdminNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCityAdminNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCityAdminNameActionPerformed

    private void btnAddZipCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddZipCodeActionPerformed
        // TODO add your handling code here:
        if(txtZipCode.getText().isEmpty()){
            JOptionPane.showMessageDialog(null,"Please enter zip code!");
            return;
        }
        this.tempNetwork.addZipCode(txtZipCode.getText());
        txtZipCode.setText("");
        populateZipCode();
    }//GEN-LAST:event_btnAddZipCodeActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        this.userProcessContainer.remove(this);
        CardLayout layout =(CardLayout) this.userProcessContainer.getLayout();
        Component [] comps = this.userProcessContainer.getComponents();
        for(Component comp : comps){
            if(comp instanceof SystemAdminRoleWorkAreaJPanel){
                SystemAdminRoleWorkAreaJPanel sarwajp =(SystemAdminRoleWorkAreaJPanel) comp;
                sarwajp.populate();
            }
        }
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnDeleteZipCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteZipCodeActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblDirectory.getSelectedRow();
        if(selectedRow>=0){
            int selectionButton = JOptionPane.YES_NO_OPTION;
            int selectionResult = JOptionPane.showConfirmDialog(null, "Are you sure to delete??","Warning",selectionButton);
            if(selectionResult == JOptionPane.YES_OPTION){
                String zipCode = (String)tblDirectory.getValueAt(selectedRow, 0);
                for(String zc: this.tempNetwork.getZipCodes()){
                    if(zc.equals(zipCode)){
                        this.tempNetwork.getZipCodes().remove(zc);
                        break;
                    }
                }                
                //dB4OUtil.storeSystem(this.ecosystem);
                populateZipCode();
            }
        }else{
            JOptionPane.showMessageDialog(null, "Please select a Row!!");
        }
    }//GEN-LAST:event_btnDeleteZipCodeActionPerformed
    
    public void populate(){
        txtCityName.setText(network.getCityName());
        txtCityAdminName.setText(network.getCityAdmin().getUser().getName());
        txtCityAdminUserName.setText(network.getCityAdmin().getUsername());
        txtCityAdminPassword.setText(network.getCityAdmin().getPassword());
        populateZipCode();
    }
    public void populateZipCode(){
        DefaultTableModel dtm = (DefaultTableModel)tblDirectory.getModel();
        dtm.setRowCount(0);   
        for(String zipCode: this.tempNetwork.getZipCodes()){
            Object[] row = new Object[dtm.getColumnCount()];
            row[0]= zipCode;
            dtm.addRow(row);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddCity;
    private javax.swing.JButton btnAddZipCode;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnDeleteZipCode;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblDirectory;
    private javax.swing.JTextField txtCityAdminName;
    private javax.swing.JTextField txtCityAdminPassword;
    private javax.swing.JTextField txtCityAdminUserName;
    private javax.swing.JTextField txtCityName;
    private javax.swing.JTextField txtZipCode;
    // End of variables declaration//GEN-END:variables
}
