/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.ngoadminrole;

import business.db4outil.DB4OUtil;
import business.config.EcoSystem;
import business.enterprise.Enterprise;
import business.network.Network;
import business.organization.Organization;
import business.role.Role;
import business.role.VolunteerRole;
import business.useraccount.UserAccount;
import business.user.User;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;


public class AddVolunteerJPanel extends javax.swing.JPanel {

    /**
     * Creates new form AddVolunteerJPanel
     */    
    JPanel userProcessContainer;
    EcoSystem ecosystem;
    UserAccount ngoAdminAccount;
    Enterprise currentEnterprise;
    private DB4OUtil dB4OUtil = DB4OUtil.getInstance();
    public AddVolunteerJPanel(JPanel userProcessContainer, EcoSystem ecosystem,UserAccount userAccount) {
        initComponents();    
        this.userProcessContainer=userProcessContainer;
        this.ecosystem=ecosystem;
        this.ngoAdminAccount = userAccount;
        initialize();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        txtVolunteerUsername = new javax.swing.JTextField();
        txtVolunteerPhoneNo = new javax.swing.JTextField();
        txtVolunteerName = new javax.swing.JTextField();
        btnAddVolunteer = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txtVolunteerPassword = new javax.swing.JPasswordField();

        setBackground(new java.awt.Color(255, 255, 240));

        jLabel1.setText("Volunteer Name");

        jLabel2.setText("Vounteer Username");

        jLabel3.setText("Volunteer Phone No.");

        jLabel4.setText("Volunteer Password");

        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        txtVolunteerUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtVolunteerUsernameActionPerformed(evt);
            }
        });

        txtVolunteerPhoneNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtVolunteerPhoneNoActionPerformed(evt);
            }
        });

        txtVolunteerName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtVolunteerNameActionPerformed(evt);
            }
        });

        btnAddVolunteer.setText("Add");
        btnAddVolunteer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddVolunteerActionPerformed(evt);
            }
        });

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/assets/images/group-of-people-gif-transparent-hd-png-download 5.27.55 PM.jpg"))); // NOI18N

        txtVolunteerPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtVolunteerPasswordActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnBack)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(57, 57, 57)
                                .addComponent(txtVolunteerName, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnAddVolunteer)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel4))
                                        .addGap(29, 29, 29))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(35, 35, 35)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtVolunteerUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtVolunteerPhoneNo, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE)
                                        .addComponent(txtVolunteerPassword)))))
                        .addGap(32, 32, 32)
                        .addComponent(jLabel5)))
                .addContainerGap(142, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(btnBack)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtVolunteerName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtVolunteerUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtVolunteerPhoneNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtVolunteerPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAddVolunteer))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jLabel5)))
                .addContainerGap(162, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtVolunteerUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtVolunteerUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtVolunteerUsernameActionPerformed

    private void txtVolunteerPhoneNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtVolunteerPhoneNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtVolunteerPhoneNoActionPerformed

    private void txtVolunteerNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtVolunteerNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtVolunteerNameActionPerformed

    private void btnAddVolunteerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddVolunteerActionPerformed
        // TODO add your handling code here:
        if(txtVolunteerName.getText().isEmpty()){
            JOptionPane.showMessageDialog(null,"Please enter volunteer name!");
            return;
        }        
        if(txtVolunteerUsername.getText().isEmpty()){
            JOptionPane.showMessageDialog(null,"Please enter volunteer username!");
            return;
        }
        for(UserAccount ua:this.ecosystem.getUserAccountDirectory().getUserAccountList()){
            if(ua.getUsername().equals(txtVolunteerUsername.getText())){
                JOptionPane.showMessageDialog(null,"Username already exists... please enter a different username!");
                return;
            }
        }
        if(txtVolunteerPhoneNo.getText().isEmpty()){
            JOptionPane.showMessageDialog(null,"Please enter volunteer phone Number!");
            return;
        }
        if(txtVolunteerPassword.getText().isEmpty()){
            JOptionPane.showMessageDialog(null,"Please enter volunteer password!");
            return;
        }

        Role role = new VolunteerRole();
        User user = ecosystem.getUserDirectory().createUser(txtVolunteerUsername.getText());
        user.setPhone(txtVolunteerPhoneNo.getText());

        
        UserAccount ua = this.ecosystem.getUserAccountDirectory().createUserAccount(txtVolunteerUsername.getText(),txtVolunteerPassword.getText() , user, role);
        outerloop:
        for(Network n:this.ecosystem.getNetworkList()){
            for(Enterprise e: n.getEnterpriseDirectory().getEnterpriseList()){
                if(e.getName().equals(this.currentEnterprise.getName())){
                    e.getUserAccountDirectory().addUserAccount(ua);
                    for(Organization o :e.getOrganizationDirectory().getOrganizationList()){
                        if(o.getName().equals(Organization.Type.Volunteer.getValue())){
                            o.getUserAccountDirectory().addUserAccount(ua);
                            System.out.println(o.getUserAccountDirectory().getUserAccountList());
                            break outerloop;
                        }
                    }
//                    e.getUserAccountDirectory().createUserAccount(txtVolunteerUsername.getText(),txtVolunteerPassword.getText() , user, role);
                    
                }
            }
        }

        dB4OUtil.storeSystem(ecosystem);
        
        clearSelections();
        
        JOptionPane.showMessageDialog(null,"Volunteer added successfully!");
        return;
    }                                                   
    public void initialize(){
        outerloop:
        for(Network n:this.ecosystem.getNetworkList()){
            for(Enterprise e :n.getEnterpriseDirectory().getEnterpriseList()){
                if(e.getUserAccount().getUsername().equals(this.ngoAdminAccount.getUsername())){
                    this.currentEnterprise = e;
                    break outerloop;
                }
            }
        }

    }//GEN-LAST:event_btnAddVolunteerActionPerformed

    public void clearSelections(){
        txtVolunteerName.setText("");
        txtVolunteerPassword.setText("");
        txtVolunteerPhoneNo.setText("");
        txtVolunteerUsername.setText("");
    }
    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        this.userProcessContainer.remove(this);
        CardLayout layout =(CardLayout) this.userProcessContainer.getLayout();
        Component [] comps = this.userProcessContainer.getComponents();
        for(Component comp : comps){
            if(comp instanceof NgoAdminRoleWorkAreaJPanel){
                NgoAdminRoleWorkAreaJPanel narwajp =(NgoAdminRoleWorkAreaJPanel) comp;
                narwajp.populateVolunteers();
            }
        }
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void txtVolunteerPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtVolunteerPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtVolunteerPasswordActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddVolunteer;
    private javax.swing.JButton btnBack;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField txtVolunteerName;
    private javax.swing.JPasswordField txtVolunteerPassword;
    private javax.swing.JTextField txtVolunteerPhoneNo;
    private javax.swing.JTextField txtVolunteerUsername;
    // End of variables declaration//GEN-END:variables
}
