/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinteraface.foodpackagingadminrole;

/**
 *
 * @author akhil
 */
public class ProcessRequestJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ProcessRequestJPanel
     */
    public ProcessRequestJPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        btnAssignToPackagingOrganization = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        lblRequestID = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        lblSender = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lblDateRequested = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblDateCompleted = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblCompletedBy = new javax.swing.JLabel();
        lblFoodPackets = new javax.swing.JLabel();
        lblMessage = new javax.swing.JLabel();
        lblStatus = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        btnAssignToPackagingOrganization1 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        lblRequestID1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        lblSender1 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        lblDateRequested1 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        lblDateCompleted1 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        lblCompletedBy1 = new javax.swing.JLabel();
        lblFoodPackets1 = new javax.swing.JLabel();
        lblMessage1 = new javax.swing.JLabel();
        lblStatus1 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox();
        btnAssignToPackagingOrganization2 = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();

        jLabel4.setText("Date Completed:");

        jLabel6.setText("Completed By:");

        jLabel7.setText("Status:");

        jLabel8.setText("Message");

        btnAssignToPackagingOrganization.setText("Send for Packaging");

        jLabel9.setText("No of Food Packets:");

        lblRequestID.setText("jLabel10");

        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        lblSender.setText("jLabel10");

        jLabel1.setText("Request ID:");

        lblDateRequested.setText("jLabel10");

        jLabel2.setText("Date Requested:");

        lblDateCompleted.setText("jLabel10");

        jLabel3.setText("Sender:");

        lblCompletedBy.setText("jLabel10");

        lblFoodPackets.setText("jLabel10");

        lblMessage.setText("jLabel10");

        lblStatus.setText("jLabel10");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel5.setText("Date Completed:");

        jLabel10.setText("Completed By:");

        jLabel11.setText("Status:");

        jLabel12.setText("Message");

        btnAssignToPackagingOrganization1.setText("Send for Delivery");

        jLabel13.setText("No of Food Packets:");

        lblRequestID1.setText("jLabel10");

        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        lblSender1.setText("jLabel10");

        jLabel14.setText("Request ID:");

        lblDateRequested1.setText("jLabel10");

        jLabel15.setText("Date Requested:");

        lblDateCompleted1.setText("jLabel10");

        jLabel16.setText("Sender:");

        lblCompletedBy1.setText("jLabel10");

        lblFoodPackets1.setText("jLabel10");

        lblMessage1.setText("jLabel10");

        lblStatus1.setText("jLabel10");

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnAssignToPackagingOrganization2.setText("Decline");
        btnAssignToPackagingOrganization2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAssignToPackagingOrganization2ActionPerformed(evt);
            }
        });

        jLabel17.setText("Delivery Man Organization:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jButton2)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16)
                    .addComponent(jLabel14)
                    .addComponent(jLabel15)
                    .addComponent(jLabel5)
                    .addComponent(jLabel10)
                    .addComponent(jLabel13)
                    .addComponent(jLabel12)
                    .addComponent(jLabel11)
                    .addComponent(jLabel17))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAssignToPackagingOrganization2)
                    .addComponent(btnAssignToPackagingOrganization1)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblStatus1)
                    .addComponent(lblMessage1)
                    .addComponent(lblFoodPackets1)
                    .addComponent(lblCompletedBy1)
                    .addComponent(lblDateCompleted1)
                    .addComponent(lblDateRequested1)
                    .addComponent(lblRequestID1)
                    .addComponent(lblSender1))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jButton2)
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(lblRequestID1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(lblSender1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(lblDateRequested1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(lblDateCompleted1))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(lblCompletedBy1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(lblFoodPackets1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(lblMessage1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(lblStatus1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAssignToPackagingOrganization1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAssignToPackagingOrganization2)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btnAssignToPackagingOrganization2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAssignToPackagingOrganization2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAssignToPackagingOrganization2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAssignToPackagingOrganization;
    private javax.swing.JButton btnAssignToPackagingOrganization1;
    private javax.swing.JButton btnAssignToPackagingOrganization2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lblCompletedBy;
    private javax.swing.JLabel lblCompletedBy1;
    private javax.swing.JLabel lblDateCompleted;
    private javax.swing.JLabel lblDateCompleted1;
    private javax.swing.JLabel lblDateRequested;
    private javax.swing.JLabel lblDateRequested1;
    private javax.swing.JLabel lblFoodPackets;
    private javax.swing.JLabel lblFoodPackets1;
    private javax.swing.JLabel lblMessage;
    private javax.swing.JLabel lblMessage1;
    private javax.swing.JLabel lblRequestID;
    private javax.swing.JLabel lblRequestID1;
    private javax.swing.JLabel lblSender;
    private javax.swing.JLabel lblSender1;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JLabel lblStatus1;
    // End of variables declaration//GEN-END:variables
}
